blank_issues_enabled: false
contact_links:
  - name: NecoVanilla
    url: https://discord.gg/NFvrkG84eD
    about: If you are having issues, My discord - sheluvyyross
  - name: NVFolia docs
    url: My server - https://discord.gg/NFvrkG84eD
    about: You can find some info at our docs
