blank_issues_enabled: false
contact_links:
  - name: EtheriumMC
    url: I sold server :)
    about: If you are having issues, My discord - sheluvyyross
  - name: EtheriumMC docs
    url: de1vaxxx
    about: You can find some info at our docs
