name: Build Pull Request

on:
  pull_request:
    branches: [ "ver/26.2" ]

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Configure Git and Gradle
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          chmod +x gradlew

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace --no-daemon

      - name: Build Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace --no-daemon

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: divinemc-server/build/libs/divinemc-paperclip-*.jar
          archive: false
